services:
  - type: web
    name: livemlb-score-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app  # Changed this line
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
